services:
  app:
    build: .
    image: ${DOCKER_USERNAME}/chatbot-tlcn:latest
    restart: always
    env_file:
      - ~/secrets.env
    depends_on:
      - postgres
      - redis
    ports:
      - "80:8000"

  postgres:
    image: pgvector/pgvector:0.7.2-pg16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_chatbot_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
  redis:
    image: redis:7.4.1
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_db_data:/var/lib/redis/data
    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
volumes:
  postgres_chatbot_data:
  redis_db_data:
