"""Edit Phone table

Revision ID: 0b47af67e745
Revises: 672acb86aec9
Create Date: 2024-11-19 23:21:08.599080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b47af67e745'
down_revision: Union[str, None] = '672acb86aec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faqs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('faqs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('phones', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('phones', sa.Column('brand_code', sa.Text(), nullable=False))
    op.add_column('phones', sa.Column('product_type_code', sa.Text(), nullable=False))
    op.add_column('phones', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('phones', sa.Column('promotions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('phones', sa.Column('skus', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('phones', sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('phones', sa.Column('key_selling_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('phones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('phones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('phones', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('phones', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('phones', 'key_selling_points')
    op.drop_column('phones', 'variants')
    op.drop_column('phones', 'skus')
    op.drop_column('phones', 'promotions')
    op.drop_column('phones', 'description')
    op.drop_column('phones', 'product_type_code')
    op.drop_column('phones', 'brand_code')
    op.drop_column('phones', 'name')
    op.alter_column('faqs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('faqs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
