"""Edit brand code column

Revision ID: 35c1ea6721f7
Revises: 0b47af67e745
Create Date: 2024-11-19 23:59:50.123136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c1ea6721f7'
down_revision: Union[str, None] = '0b47af67e745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phones', 'brand_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('phones', 'product_type_code',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phones', 'product_type_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('phones', 'brand_code',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
